name: hive_food_delivery
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.3.2
  smooth_page_indicator: ^1.2.1
  get: ^4.7.2
  get_storage: ^2.1.1
  form_builder: ^1.0.1
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.1.0
  iconsax: ^0.0.8
  carousel_slider: ^5.1.1
  remixicon: ^1.4.1
  flutter_native_splash: ^2.4.6
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.3.0
  provider: ^6.1.5+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # ✅ REQUIRED FOR APP ICON
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/animation/
    - assets/images/
    - assets/food images/
    - assets/banners/
    - assets/logos/
    - assets/product images/
    - assets/category/
    - assets/lottie/

# ✅ MUST BE OUTSIDE flutter:
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/Logo2-1.png"
  min_sdk_android: 21